FROM registry.access.redhat.com/ubi8/python-311:1@sha256:22a463b4c203a37d827d768a003710f253cd29f2949bf0f4d19c4d687d5a94d0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json

LABEL com.redhat.component="odh-feature-server" \
      name="odh-feature-server-rhel8" \
      description="odh-feature-server" \
      summary="odh-feature-server" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-feature-server" \
      io.k8s.description="odh-feature-server"